from services.src.html_string import made_text

page_prueba = made_text("https://joanribot.github.io/Sandbox0")
page_prueba2 = made_text("https://joanribot.github.io/Sandbox0/enlace3")
page_prueba3 = made_text("https://joanribot.github.io/Sandbox0/enlace4")

tipoMedicamento = ["AINE", "Diuretico", "Antihipertensivo", "Benzodiazepina", "Hipolipemiante", "Antidepresivo"]
htmlMedicamentosPequeño = '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Document</title></head><body><p class="AINE">Ibuprofeno</p><p class="Diuretico">Furosemida</p><p class="Antihipertensivo">Ramipril</p><p class="Benzodiazepina">Diazepam</p><p class="Hipolipemiante">Simvastatina</p><p class="Antidepresivo">Fluoxetina</p></html>'
htmlMedicamentosGrande = '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Document</title></head><body><h1><p class="AINE">Dexketoprofeno</p><p class="Diuretico">Torasemida</p><p class="Antihipertensivo">Enalapril</p><p class="Benzodiazepina">Lorazepam</p><p class="Hipolipemiante">Atorvastatina</p><p class="Antidepresivo">Duloxetina</p></h1><h2><p class="AINE">Ibuprofeno</p><p class="Diuretico">Furosemida</p><p class="Antihipertensivo">Ramipril</p><p class="Benzodiazepina">Diazepam</p><p class="Hipolipemiante">Simvastatina</p><p class="Antidepresivo">Fluoxetina</p></h2><h3><p class="AINE">Naproxeno</p><p class="Diuretico">Indapamida</p><p class="Antihipertensivo">Lisinopril</p><p class="Benzodiazepina">Alprazolam</p><p class="Hipolipemiante">Rosuvastatina</p><p class="Antidepresivo">Escitalopram</p></h2></h3></html>'

htmlsAnimales = ['<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title class="lugar">mamifero</title></head><body><h1 class="primero">Mono</h1><h1 class="segundo">Rata</h1><h1 class="tercero">ornitorrinco</h1><h1 class="primero">Ardilla</h1><h1 class="segundo">Ratón</h1><h1 class="tercero">Cabra</h1></body></html>','<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title class="lugar">ave</title></head><body><h1 class="primero">Loro</h1><h1 class="segundo">Avestruz</h1><h1 class="tercero">Gallina</h1> <h1 class="primero">Gaviota</h1><h1 class="segundo">Paloma</h1><h1 class="tercero">Colibrí</h1></body></html>','<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title class="lugar">Bicho</title></head><body><h1 class="primero">hormiga</h1><h1 class="segundo">mosquito</h1><h1 class="tercero">escarabajo</h1><h1 class="primero">dragonfly</h1><h1 class="segundo">mosca</h1><h1 class="tercero">abeja</h1></body></html>']
